CREATE TABLE IF NOT EXISTS PRODUCT (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NOME_DO_PRODUTO VARCHAR(100),
    NOME_DO_FABRICANTE VARCHAR(100),
    CATEGORIA VARCHAR(100),
    PRECO FLOAT,
    PRIMARY KEY (ID)
    
);
CREATE TABLE IF NOT EXISTS MANUFACTURER (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NOME_DO_FABRICANTE VARCHAR(50),
    CATEGORIA1 VARCHAR(50),
    CATEGORIA2 VARCHAR(50),
    CATEGORIA3 VARCHAR(50),
    PRIMARY KEY (ID)
    
);